import { useQuery } from "@tanstack/react-query";
import { api } from "../services/api";

const categoryLabels: Record<string, string> = { TOURNAMENT_SCENARIO: "赛事阵容", HISTORICAL_MATCHES: "历史比赛", TEAM_STRENGTH: "球队实力", OFFICIAL_RANKING: "官方排名", TOURNAMENT_RULES: "赛事规则" };

export default function DataSourcesPage() {
  const { data, isLoading, error } = useQuery({ queryKey: ["data-sources"], queryFn: api.getDataSources, staleTime: 300000 });
  return <div className="mx-auto max-w-6xl px-4 py-6 sm:px-6">
    <header className="mb-6 border-b border-[var(--color-border)] pb-5"><span className="dashboard-label text-[var(--color-primary)]">DATA PROVENANCE</span><h1 className="dashboard-title mt-2">真实数据来源与采集证据</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--color-text-muted)]">公开展示模型使用的数据、核验入口、本地快照与校验值。只有具备本地 SHA-256 的项目才标记为已经验证。</p></header>
    {isLoading && <div className="dashboard-card p-8 text-center text-sm text-[var(--color-text-muted)]">正在读取数据证据……</div>}
    {error && <div className="dashboard-card border-[var(--color-error)]/50 p-5 text-[var(--color-error)]">{error instanceof Error ? error.message : "数据证据加载失败"}</div>}
    {data && <><section className="dashboard-card mb-5 border-[var(--color-primary)]/30 p-4"><div className="flex flex-wrap gap-3"><span className="rounded-full bg-[var(--color-secondary)]/15 px-3 py-1 text-sm text-[var(--color-secondary)]">{data.verified_local_sources} 项本地证据已校验</span><span className="rounded-full border border-[var(--color-border)] px-3 py-1 text-sm text-[var(--color-text-muted)]">{data.pending_network_sources} 项待联网刷新</span><span className="rounded-full border border-[var(--color-border)] px-3 py-1 font-mono text-xs text-[var(--color-text-muted)]">清单 {data.manifest_version}</span></div><p className="mt-3 text-sm leading-6 text-[var(--color-text-muted)]">{data.transparency_notice}</p></section>
      <div className="grid gap-4 lg:grid-cols-2">{data.sources.map((source) => <article key={source.id} className="dashboard-card flex flex-col p-5"><div className="flex items-start justify-between gap-3"><div><span className="text-xs text-[var(--color-text-muted)]">{categoryLabels[source.category] ?? source.category} · {source.provider}</span><h2 className="mt-1 text-lg font-semibold text-white">{source.name}</h2></div><span className={`shrink-0 rounded-full border px-2 py-1 text-xs ${source.verification_status === "VERIFIED_LOCAL" ? "border-[var(--color-secondary)]/50 text-[var(--color-secondary)]" : "border-[var(--color-primary)]/50 text-[var(--color-primary)]"}`}>{source.verification_status === "VERIFIED_LOCAL" ? "本地已校验" : "待联网刷新"}</span></div><p className="mt-3 text-sm leading-6 text-[var(--color-text-muted)]">{source.notice}</p><div className="mt-4 flex flex-wrap gap-2">{source.used_by.map((item) => <span key={item} className="rounded-md bg-[var(--color-surface-raised)] px-2 py-1 text-xs text-[var(--color-text-muted)]">用于：{item}</span>)}</div>{source.snapshot_sha256 && <div className="mt-4 space-y-2 border-t border-[var(--color-border)] pt-4 text-xs"><p><span className="text-[var(--color-text-muted)]">记录数：</span>{source.record_count ?? "—"}　<span className="text-[var(--color-text-muted)]">大小：</span>{source.snapshot_bytes} 字节</p><p className="break-all font-mono text-[var(--color-text-muted)]"><span className="font-sans text-white">SHA-256：</span>{source.snapshot_sha256}</p><p className="text-[var(--color-text-muted)]">快照更新时间：{source.snapshot_modified_at ? new Date(source.snapshot_modified_at).toLocaleString("zh-CN") : "—"}</p></div>}{source.source_url && <a href={source.source_url} target="_blank" rel="noreferrer" className="mt-4 inline-flex w-fit text-sm font-semibold text-[var(--color-primary)] hover:underline">查看公开来源 ↗</a>}{source.is_official && <span className="mt-3 text-xs text-[var(--color-secondary)]">FIFA 官方来源入口</span>}</article>)}</div>
    </>}
  </div>;
}
